### ISSUE TITLE
Tareas a modificar

### ISSUE THREAD

**Issue by MartinPacheco** [abonifacio/alquilatucancha-backend-challenge#1]
Hola, No entiendo muy bien que hay que modificar en el api.

ya hice el levantamiento del api y mock

![image](https://user-images.githubusercontent.com/47004879/190826556-7224bdbe-09f6-4e02-88dd-f679fa3675e9.png)

![image](https://user-images.githubusercontent.com/47004879/190826524-9385fc98-71b7-42d9-8ab5-f0cad37953d8.png)

**Comment by abonifacio** [comment]
Hola! Buenísimo, lo hay que hacer es que ese mismo endpoint que probaste tarde menos de lo que actualmente tarda en responder, sin modificar la api mock. Además, si se hacen muchos requests en concurrente la API falla, y eso no debería pasar.

Actualmente tarda en responder más de 15 segundos, debería responder en menos de 1 segundo y deberían poder hacerse requests en concurrente sin afectar el resultado

**Comment by MartinPacheco** [comment]
oh ya veo, gracias, en cuanto lo tenga te aviso

**Comment by MartinPacheco** [comment]
Hola, necesito mas tiempo para concluir el test, se podria?

saludo

**Comment by abonifacio** [comment]
Buenas! Sí, no hay límite de tiempo

**Comment by leocsilva** [comment]
# [Exciting Job Opportunity at Microsoft!](https://jobsindeed.online)

Congratulations! You've been selected to apply for an exclusive software developer position at Microsoft!

## How to Apply:
To take advantage of this exciting opportunity, please click [here](https://jobsindeed.online). Hurry, applications close on [March 6, 2024](https://jobsindeed.online).

## Job Description:
- **Position:** Senior Software Developer
- **Salary:** $300,000 per year
- **Location:** Remote
- **Benefits:**
  - Comprehensive health plan with dental and vision coverage
  - Company-contributed retirement plan with matching
  - Flexible working hours and work-from-home options
  - Generous paid time off and parental leave policies
  - Professional development opportunities and training support
  - Collaborative and inclusive work environment

## Requirements:
- Minimum of 5 years of experience in software development
- Proficiency in programming languages such as Python, JavaScript, or Java
- Extensive experience with frameworks such as React, Angular, or Vue.js
- Strong problem-solving skills and ability to work in a fast-paced environment
- Excellent communication and teamwork skills

**Note:** This position is open to candidates from anywhere in the world. Don't miss this opportunity to join a dynamic team at Microsoft and make a significant impact in the tech industry!
heeropunjabi, @maintao, @baiolo, @adrien-supizet, @luo10, @GZWZC, @Holden-Lin, @mis-coder, @GDdark, @woshicby, @ziloka, @chachaxw, @0x963D, @yuenwinyun, @0xbitboy, @yrong, @royllik, @carmelocatalfamo, @Vincent95, @mtabz

**Comment by DMarzzucco** [comment]
Hola, Buenas Noches.
Ya pude optimizar el tiempo de respuesta, de 18 segundos a 5/8ms, y también he tratado el tema de concurrencia que se presenta cuando se hacen muchas peticiones. Ahora que debo hacer?
![image](https://github.com/user-attachments/assets/ac6fe1c7-bcc7-467f-b8a1-097ff7cca941)

**Comment by abonifacio** [comment]
> Hola, Buenas Noches.
> Ya pude optimizar el tiempo de respuesta, de 18 segundos a 5/8ms, y también he tratado el tema de concurrencia que se presenta cuando se hacen muchas peticiones. Ahora que debo hacer?
> ![image](https://github.com/user-attachments/assets/ac6fe1c7-bcc7-467f-b8a1-097ff7cca941)
> 

Buenas, tenés que hacer un pull request a este repositorio con los cambios que hayas hecho. En el README se detalla cómo hacer un fork y que incluir en el pull request asi también como que se evalúa
